### ISSUE TITLE
A few instances of <em> should be <i>

### ISSUE THREAD

**Issue by drgrigg** [vr8hub/solomon-northup_twelve-years-a-slave#1]
In chapter 22, line 16, you have a header which uses <em> for italics. They aren't emphasised speech so they should be <i>, I would say.

**Comment by vr8hub** [comment]
You didn't backquote your tags, so they disappeared. :) I'm assuming you meant used `<em>` for tags and should be `<i>`. Yes, absolutely, they got caught in a bulk update and I didn't notice they were wrong. Fixed. (If that's _not_ what you meant, then let me know.)

**Comment by drgrigg** [comment]
That was what I meant. Should have read:

In chapter 22, line 16, you have a header which uses `<em>` for italics. They aren't emphasised speech so they should be `<i>`, I would say.
