### ISSUE TITLE
Cover and title page breaks

### ISSUE THREAD

**Issue by drgrigg** [vr8hub/solomon-northup_twelve-years-a-slave#2]
Wouldn't they be better as:

TWELVE YEARS
A SLAVE

Rather than (as now)

TWELVE
YEARS A SLAVE

**Comment by vr8hub** [comment]
I started to say I never mess with the auto-generation, but then I remembered I actually did for _Decline and Fall_, so I'll say instead that it's never looked "off" to me. (I have an internal bias against first lines being longer than the second line.) But, I'm happy to make the change; fixed.

**Comment by vr8hub** [comment]
Pushed.
