### ISSUE TITLE
Should "Chorus" be a sub-heading rather than just a line in the song?

### ISSUE THREAD

**Issue by drgrigg** [vr8hub/solomon-northup_twelve-years-a-slave#4]
In Chapter 15, you have a couple of songs with choruses, and the word "Chorus" has unsemanticated `<i>` tags. 

I'm wondering if we shouldn't treat these as though they were headings rather than as a spanned line in the song? We've dealt with this kind of thing in poetry before, where we've used a surrounding `<div><header> ... </header></div>` structure. It might be overkill, though!

**Comment by drgrigg** [comment]
Same issue at the end of Chapter 22.

**Comment by vr8hub** [comment]
Yes, I thought about that oh so briefly and decided that 1) "Chorus" didn't feel like a header to me, and 2) It would be overkill. :) But, I'm happy to make the change if you feel differently. (I did that in _Ben Hur_, but there it really was a header, i.e. a title.)

**Comment by drgrigg** [comment]
Let's leave it unless Alex thinks otherwise.
